const data = [
    {
        date: "Mardi 01/03/22",
        consultationMethod: "en Présentiel",
        time: "14:00",
        doctor: "Dr Amsalem David",
        appointmentType: "Consultation",
        patientName: "brayan brayan",
        patientPhone: "459329299292",
        patientEmail: "nteguemroland@yahoo.com",
        addressName: "Demo Medecins",
        addressLine1: "75011 Paris",
        addressLine2: "136 rue de charonne",
        addressPhone: "0102030903",
        mode: "prepaiementRdvTelephonique"
    },
    {
        date: "Mercredi 02/03/22",
        consultationMethod: "par Téléphone",
        time: "15:30",
        doctor: "Dr Smith John",
        appointmentType: "Teleconsultation",
        patientName: "Alice Johnson",
        patientPhone: "1234567890",
        patientEmail: "alice@example.com",
        addressName: "Clinique ABC",
        addressLine1: "78945 Lille",
        addressLine2: "123 rue de la Santé",
        addressPhone: "9876543210",
        mode: "teleconsultation"
    },
    {
        date: "Jeudi 03/03/22",
        consultationMethod: "en Présentiel",
        time: "09:00",
        doctor: "Dr Dupont Pierre",
        appointmentType: "Consultation",
        patientName: "Jean Dupont",
        patientPhone: "987654321",
        patientEmail: "jean.dupont@example.com",
        addressName: "Cabinet Médical XYZ",
        addressLine1: "78945 Lille",
        addressLine2: "456 avenue du Docteur",
        addressPhone: "123456789",
        mode: "teleconsultation"
    },
    {
        date: "Vendredi 04/03/22",
        consultationMethod: "en Présentiel",
        time: "11:45",
        doctor: "Dr Garcia Maria",
        appointmentType: "Consultation",
        patientName: "Maria Garcia",
        patientPhone: "5555555555",
        patientEmail: "maria.garcia@example.com",
        addressName: "Clinique ZZZ",
        addressLine1: "78945 Lille",
        addressLine2: "789 boulevard de la Santé",
        addressPhone: "1111111111",
        mode: "cancel"
    },
    {
        date: "Samedi 05/03/22",
        consultationMethod: "par Téléphone",
        time: "16:00",
        doctor: "Dr Johnson Mark",
        appointmentType: "Téléconsultation",
        patientName: "Mark Johnson",
        patientPhone: "6666666666",
        patientEmail: "mark.johnson@example.com",
        addressName: "Clinique CCC",
        addressLine1: "78945 Lille",
        addressLine2: "321 rue de la Santé",
        addressPhone: "2222222222",
        mode: "prepaiementRdvTelephonique"
    },
    {
        date: "Dimanche 06/03/22",
        consultationMethod: "en Présentiel",
        time: "13:30",
        doctor: "Dr Martinez Laura",
        appointmentType: "Examen",
        patientName: "Laura Martinez",
        patientPhone: "7777777777",
        patientEmail: "laura.martinez@example.com",
        addressName: "Clinique EEE",
        addressLine1: "78945 Lille",
        addressLine2: "987 boulevard de la Santé",
        addressPhone: "3333333333",
        mode: "rdvExist"
    },
]

export default data;
