export const UNSUBSCRIBE_ACCOUNT_FAILURE = 'UNSUBSCRIBE_ACCOUNT_FAILURE';
export const UNSUBSCRIBE_ACCOUNT_REQUEST = 'UNSUBSCRIBE_ACCOUNT_REQUEST';
export const UNSUBSCRIBE_ACCOUNT_SUCCESS = 'UNSUBSCRIBE_ACCOUNT_SUCCESS';
export const INFORMATION_ACCOUNT_FAILURE = 'INFORMATION_ACCOUNT_FAILURE';
export const INFORMATION_ACCOUNT_REQUEST = 'INFORMATION_ACCOUNT_REQUEST';
export const INFORMATION_ACCOUNT_SUCCESS = 'INFORMATION_ACCOUNT_SUCCESS';
