export const types = {
    GET_COUNTRIES_REQUEST: 'GET_COUNTRIES_REQUEST',
    GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
    GET_COUNTRIES_FAILURE: 'GET_COUNTRIES_FAILURE',
    GET_COUNTRY_DETAILS_REQUEST: 'GET_COUNTRY_DETAILS_REQUEST',
    GET_COUNTRY_DETAILS_SUCCESS: 'GET_COUNTRY_DETAILS_SUCCESS',
    GET_COUNTRY_DETAILS_FAILURE: 'GET_COUNTRY_DETAILS_FAILURE',
  };
  