export const LIST_APPOINTMENT_REQUEST = 'LIST_APPOINTMENT_REQUEST';
export const LIST_APPOINTMENT_SUCCESS = 'LIST_APPOINTMENT_SUCCESS';
export const LIST_APPOINTMENT_FAILURE = 'LIST_APPOINTMENT_FAILURE';

export const CREATE_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAILURE = 'CREATE_APPOINTMENT_FAILURE';
export const STEP_REQUEST = 'STEP_REQUEST'; 
