export const LIST_APPOINTMENT_REQUEST = 'LIST_APPOINTMENT_REQUEST';
export const LIST_APPOINTMENT_SUCCESS = 'LIST_APPOINTMENT_SUCCESS';
export const LIST_APPOINTMENT_FAILURE = 'LIST_APPOINTMENT_FAILURE';

export const CREATE_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAILURE = 'CREATE_APPOINTMENT_FAILURE';

export const LIST_DOCTOR_REQUEST = 'LIST_DOCTOR_REQUEST';
export const LIST_DOCTOR_SUCCESS = 'LIST_DOCTOR_SUCCESS';
export const LIST_DOCTOR_FAILURE = 'LIST_DOCTOR_FAILURE';

export const REMOVE_DOCTOR_REQUEST = 'REMOVE_DOCTOR_REQUEST';
export const REMOVE_DOCTOR_SUCCESS = 'REMOVE_DOCTOR_SUCCESS';
export const REMOVE_DOCTOR_FAILURE = 'REMOVE_DOCTOR_FAILURE';
export const REMOVE_DOCTOR_FORBIDDEN  = 'REMOVE_DOCTOR_FORBIDDEN ';

export const LIST_PATIENT_REQUEST = 'LIST_PATIENT_REQUEST';
export const LIST_PATIENT_SUCCESS = 'LIST_PATIENT_SUCCESS';
export const LIST_PATIENT_FAILURE = 'LIST_PATIENT_FAILURE';

export const PAIEMENT_APPOINTMENT_REQUEST = 'PAIEMENT_APPOINTMENT_REQUEST';
export const PAIEMENT_APPOINTMENT_SUCCESS = 'PAIEMENT_APPOINTMENT_SUCCESS';
export const PAIEMENT_APPOINTMENT_FAILURE = 'PAIEMENT_APPOINTMENT_FAILURE';
