export const LIST_APPOINTMENT_REQUEST = 'LIST_APPOINTMENT_REQUEST';
export const LIST_APPOINTMENT_SUCCESS = 'LIST_APPOINTMENT_SUCCESS';
export const LIST_APPOINTMENT_FAILURE = 'LIST_APPOINTMENT_FAILURE';

export const CREATE_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAILURE = 'CREATE_APPOINTMENT_FAILURE';

export const LIST_DOCTOR_REQUEST = 'LIST_DOCTOR_REQUEST';
export const LIST_DOCTOR_SUCCESS = 'LIST_DOCTOR_SUCCESS';
export const LIST_DOCTOR_FAILURE = 'LIST_DOCTOR_FAILURE';

export const PAIEMENT_APPOINTMENT_REQUEST = 'PAIEMENT_APPOINTMENT_REQUEST';
export const PAIEMENT_APPOINTMENT_SUCCESS = 'PAIEMENT_APPOINTMENT_SUCCESS';
export const PAIEMENT_APPOINTMENT_FAILURE = 'PAIEMENT_APPOINTMENT_FAILURE';
