export const MAKE_PAIEMENT_REQUEST = 'MAKE_PAIEMENT_REQUEST';
export const MAKE_PAIEMENT_SUCCESS = 'MAKE_PAIEMENT_REQUEST_SUCCESS';
export const MAKE_PAIEMENT_FAILURE = 'MAKE_PAIEMENT_REQUEST_FAILURE';
